# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - http://cdn.redrock.team/hello-student_music1.mp3
    - http://cdn.redrock.team/hello-student_music1.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/qq1-cover.jpg
  - /img/qq2-cover.jpg
  - /img/qq3-cover.jpg
  - /img/qq4-cover.jpg
  - /img/qq5-cover.jpg
  - /img/qq6-cover.jpg
  - /img/qq7-cover.jpg
  - /img/qq8-cover.jpg
  - /img/qq9-cover.jpg
  - /img/qq10-cover.jpg
  - /img/qq11-cover.jpg
  - /img/qq12-cover.jpg
  - /img/qq13-cover.jpg
  - /img/qq14-cover.jpg
  - /img/qq15-cover.jpg
  - /img/qq16-cover.jpg
  - /img/qq17-cover.jpg
  - /img/qq18-cover.jpg
  - /img/qq19-cover.jpg
  - /img/qq20-cover.jpg
  - /img/qq21-cover.jpg
  - /img/qq22-cover.jpg
  - /img/qq23-cover.jpg
  - /img/qq24-cover.jpg
  - /img/qq25-cover.jpg
  - /img/qq1-cover.png
  - /img/qq1-cover.png
  - /img/qq2-cover.png
  - /img/qq3-cover.png
  - /img/qq4-cover.png
  - /img/qq5-cover.png
  - /img/qq6-cover.png
  - /img/qq7-cover.png
  - /img/qq8-cover.png
  - /img/qq9-cover.png
  - /img/qq10-cover.png
  - /img/qq11-cover.png
  - /img/qq12-cover.png
  
# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: /
    twitter: /
    github: https://github.com/myjdml
    wechat: /img/logo.png
    email: mailto:myjdml_codemaster@163.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: true
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'b6ecefc4bbca5c566933'
    # 应用秘钥
    clientSecret: 'ee266e05d6d467746681de2690e39a5aafe7276d'
    # issue仓库名
    repo: 'myjdml.github.io'
    # Github名
    owner: 'myjdml'
    # Github名
    admin: ['myjdml']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    lables: 'gitalk'
    # Facebook-like distraction free mode
    distractionFreeMode: true

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
